export const VACATIONS_SUCCESS='VACATIONS_SUCCESS'
export const VACATIONS_FAIL='VACATIONS_FAIL'

export const LIKE_VACATION='LIKE_VACATION'
export const UNFOLLOW='UNFOLLOW'
export const SET_FOLLOWERS='SET_FOLLOWERS'
export const FETCH_FOLLOWERS='FETCH_FOLLOWERS'

export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAIL = "USER_FAIL";
export const USER_LOGOUT = "USER_LOGOUT"

export const UNREFRESH = "UNREFRESH"

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const TOKEN = "TOKEN";

export const DELETE_VACATION='DELETE_VACATION'
export const ADD_VACATION='ADD_VACATION'
export const EDIT_VACATION='EDIT_VACATION'

